### ISSUE TITLE
error_wrong_ip or 403 

### ISSUE THREAD

**Issue by Love656** [khalisafkari/google-photos-etc#4]
error_wrong_ip or 403
https://khalis-khalis411.now.sh/cloudvideo?url=https://cloudvideo.tv/42xcdwiwamlh
Url video not work

**Comment by khalisafkari** [comment]
please try on your own server,

**Comment by khalisafkari** [comment]
I use the free version of zeit, the time to execute the video in cloudvideo.tv is not enough

**Comment by khalisafkari** [comment]
the video has been deleted by cloudvideo.tv you can try your own video or https://khalis-khalis411.now.sh/cloudvideo?url=https://cloudvideo.tv/wnjb1hz5ccdd

**Comment by Love656** [comment]
Hls and mp4 url 
![Screenshot_20190625_110540_com android chrome](https://user-images.githubusercontent.com/32559246/60080829-4d75b300-9739-11e9-97ab-c436a1db0633.jpg)
![Screenshot_20190625_110528_com android chrome](https://user-images.githubusercontent.com/32559246/60080830-4d75b300-9739-11e9-8994-43accb5a5c05.jpg)

**Comment by khalisafkari** [comment]
the problem occurs because they limit ip, please try your localhost, or you can change the ip header request must be the same as ip when you do request
